services:

  redis-database:
    container_name: redis-database
    hostname: redis-database
    image: redis:8.0.0
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
